In [ ]:
# Excel Sheet -> Python Reads or Ingests -> Pandas organizes it

import pandas as pd
import numpy as np

In [16]:
# DataFrame
data = {
    "product": ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    "price": [1200.50, 25.00, 45.99, 3500.00],
    "quantity": [2, 20, 10, 5]
}

df = pd.DataFrame(data)
df

    product    price  quantity
0    Laptop  1200.50         2
1     Mouse    25.00        20
2  Keyboard    45.99        10
3   Monitor  3500.00         5

In [ ]:
# Reading data from CSV
df_sales = pd.read_csv('raw_sales_data.csv')
df_sales

  Transaction ID customer_id       Product_Name   Amount  Order Date Region
0           1001        C001             Laptop  1200.50  2023-01-15  North
1           1002        C002              mouse    25.00  01/16/2023  south
2           1003         NaN  Wireless Keyboard    45.99  2023-01-17  North
3           1004        C001            Monitor      NaN  2023-01-18   WEST
4           1005        C003             laptop  1200.50  2023-02-19  North
5           1006        C004                NaN    15.00  2023-02-20   East
6      ERROR_ROW        9999               Junk     0.00  00/00/0000    NaN

In [6]:
df_sales.head()

  Transaction ID customer_id       Product_Name   Amount  Order Date Region
0           1001        C001             Laptop  1200.50  2023-01-15  North
1           1002        C002              mouse    25.00  01/16/2023  south
2           1003         NaN  Wireless Keyboard    45.99  2023-01-17  North
3           1004        C001            Monitor      NaN  2023-01-18   WEST
4           1005        C003             laptop  1200.50  2023-02-19  North

In [8]:
df_sales['Amount']

0    1200.50
1      25.00
2      45.99
3        NaN
4    1200.50
5      15.00
6       0.00
Name: Amount, dtype: float64

In [ ]:
# Filtering
df_sales[(df_sales["Amount"]> 1000) & (df_sales["customer_id"]=="C001")]

  Transaction ID customer_id Product_Name  Amount  Order Date Region
0           1001        C001       Laptop  1200.5  2023-01-15  North

In [17]:
# Calculations
df['total_sales'] = df["price"] * df['quantity']
df

    product    price  quantity  total_sales
0    Laptop  1200.50         2       2401.0
1     Mouse    25.00        20        500.0
2  Keyboard    45.99        10        459.9
3   Monitor  3500.00         5      17500.0

In [20]:
# Group By
ts = df.groupby('product')['total_sales'].sum()

In [ ]:
# Sort Values
ts = ts.sort_values(ascending=False)
ts

product
Monitor     17500.0
Laptop       2401.0
Mouse         500.0
Keyboard      459.9
Name: total_sales, dtype: float64

In [ ]:
# Output as CSV file
ts.to_csv('sales_by_product.csv')

In [19]:
df.sort_values("total_sales", ascending = False)

    product    price  quantity  total_sales
3   Monitor  3500.00         5      17500.0
0    Laptop  1200.50         2       2401.0
1     Mouse    25.00        20        500.0
2  Keyboard    45.99        10        459.9

In [4]:
df_customers = pd.read_csv('dim_customers.csv')
df_customers

  customer_id    customer_name         segment
0        C001  Alice Tech Corp       Corporate
1        C002        Bob Reyes        Consumer
2        C003   Charlie's Shop  Small Business
3        C004        David Lim        Consumer