In [17]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

Pandas - Series

In [18]:
sales_index = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
sales_values = [500, 200, 300, 200, 100]

sales_series = pd.Series(sales_values, index=sales_index)
sales_series

Monday       500
Tuesday      200
Wednesday    300
Thursday     200
Friday       100
dtype: int64

In [19]:
sales = {
    'Monday': 500,
    'Tuesday': 200,
    'Wednesday': 300,
    'Thursday': 150,
    'Friday': 175
}

sales_series_dict = pd.Series(sales)
sales_series_dict

Monday       500
Tuesday      200
Wednesday    300
Thursday     150
Friday       175
dtype: int64

In [20]:
# Acccessing Data

# []
sales_series_dict[1]
sales_series_dict['Tuesday']

200

In [21]:
# [[]]
sales_series_dict[[0]]

Monday    500
dtype: int64

In [22]:
# [:]
sales_series_dict[:3]

Monday       500
Tuesday      200
Wednesday    300
dtype: int64

In [23]:
# [[n, n, n]]

sales_series_dict[[0, 2, 4]]

Monday       500
Wednesday    300
Friday       175
dtype: int64

In [26]:
# [condition]
sales_series_dict[sales_series_dict>=300]

Monday       500
Wednesday    300
dtype: int64

Series Operations

In [28]:
sales_series_dict + sales_series_dict

Monday       1000
Tuesday       400
Wednesday     600
Thursday      300
Friday        350
dtype: int64

Numpy Array

In [24]:
s = pd.Series(np.random.randn(10))
s

0   -0.925984
1    0.790413
2   -1.048822
3   -0.038621
4    1.854395
5    1.226041
6   -0.071555
7    0.636159
8   -1.194679
9    1.409830
dtype: float64

Pandas - DataFrame

In [61]:
sales_month = {
    'Monday': [200, 250, 120, 500],
    'Tuesday': [100, 200, 300, 400],
    'Wednesday': [100, 150, 160, 109],
    'Thursday': [530,520,106,806],
    'Friday': [900, 899, 121, 949]
}

week_index = ['week1', 'week2', 'week3', 'week4']
test_series = pd.DataFrame(sales_month, index=week_index)
test_series['weekly_total'] = test_series.sum(axis=1)

test_series

       Monday  Tuesday  Wednesday  Thursday  Friday  weekly_total
week1     200      100        100       530     900          1830
week2     250      200        150       520     899          2019
week3     120      300        160       106     121           807
week4     500      400        109       806     949          2764

In [35]:
test_series.T

              week1  week2  week3  week4
Monday          200    250    120    500
Tuesday         100    200    300    400
Wednesday       100    150    160    109
Thursday        530    520    106    806
Friday          900    899    121    949
weekly_total   1830   2019    807   2764

In [36]:
# iloc

test_series.iloc[2:3, 3:4]

       Thursday
week3       106

In [44]:
# loc
test_series.loc[['week1', 'week4'], ['Monday', 'Wednesday']]

       Monday  Wednesday
week1     200        100
week4     500        109

In [77]:
new_series = test_series.T
new_series

              week1  week2  week3  week4
Monday          200    250    120    500
Tuesday         100    200    300    400
Wednesday       100    150    160    109
Thursday        530    520    106    806
Friday          900    899    121    949
weekly_total   3760   4238   1914   5928
Saturday        100    200    300    400

In [78]:
new_series.loc['Saturday'] = [100, 200, 300, 400]
new_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

new_series = new_series.reindex(new_order)
new_series

           week1  week2  week3  week4
Monday       200    250    120    500
Tuesday      100    200    300    400
Wednesday    100    150    160    109
Thursday     530    520    106    806
Friday       900    899    121    949
Saturday     100    200    300    400

In [79]:
new_series.loc['weekly_total'] = new_series.sum(axis=0)
new_series

              week1  week2  week3  week4
Monday          200    250    120    500
Tuesday         100    200    300    400
Wednesday       100    150    160    109
Thursday        530    520    106    806
Friday          900    899    121    949
Saturday        100    200    300    400
weekly_total   1930   2219   1107   3164

In [82]:
new_series.drop('weekly_total')
new_series

              week1  week2  week3  week4
Monday          200    250    120    500
Tuesday         100    200    300    400
Wednesday       100    150    160    109
Thursday        530    520    106    806
Friday          900    899    121    949
Saturday        100    200    300    400
weekly_total   1930   2219   1107   3164

In [83]:
# Filling of Data

In [86]:
sales_month = {
    'Monday': [200, 250, 120, 500],
    'Tuesday': [100, 200, None, 400],
    'Wednesday': [100, 150, 160, 109],
    'Thursday': [530, None,106,806],
    'Friday': [900, 899, 121, 949]
}

sales = pd.DataFrame(sales_month)
sales

   Monday  Tuesday  Wednesday  Thursday  Friday
0     200    100.0        100     530.0     900
1     250    200.0        150       NaN     899
2     120      NaN        160     106.0     121
3     500    400.0        109     806.0     949

In [89]:
clean_sales = sales.fillna(sales.mean())
clean_sales

   Monday     Tuesday  Wednesday    Thursday  Friday
0     200  100.000000        100  530.000000     900
1     250  200.000000        150  480.666667     899
2     120  233.333333        160  106.000000     121
3     500  400.000000        109  806.000000     949

In [90]:
drop_sales = sales.dropna()
drop_sales

   Monday  Tuesday  Wednesday  Thursday  Friday
0     200    100.0        100     530.0     900
3     500    400.0        109     806.0     949

In [92]:
check_sales = sales.isna().sum()
check_sales

Monday       0
Tuesday      1
Wednesday    0
Thursday     1
Friday       0
dtype: int64